### ISSUE TITLE
Pas de dossier site/ sur Github

### ISSUE THREAD

**Issue by bazooka07** [pluxml/PluXml-Wiki#2]
Vu que le dossier site/ est généré par Mkdocs, il semble inutile de la partager sur Github.
Cela risque de poser problème quand on poste un post-request.

Voir recommendation de Mkdocs :
https://www.mkdocs.org/#building-the-site

> If you're using source code control such as git you probably don't want to check your documentation builds into the repository.

**Comment by haruka-7** [comment]
Effectivement j'ai oublié le gitignore.
C'est corrigé.
